type
    INT8* = int8
    PINT8* = ptr int8
    INT32* = int32
    PINT32* = ptr int32
    INT64* = int64
    PINT64* = ptr int64
    UINT8* = uint8
    PUINT8* = ptr uint8
    UINT16* = uint16
    PUINT16* = ptr uint16
    UINT32* = int32
    PUINT32* = ptr int32
    UINT64* = int64
    PUINT64* = ptr int64
    LONG32* = int32
    PLONG32* = ptr int32
    ULONG32* = int32
    PULONG32* = ptr int32
    DWORD32* = int32
    PDWORD32* = ptr int32
    LONG64* = int64
    PLONG64* = ptr int64
    ULONG64* = int64
    PULONG64* = ptr int64
    DWORD64* = int64
    PDWORD64* = ptr int64
    PVOID* = pointer
    CHAR* = char
    LONG* = int32
    INT* = int32
    UCHAR* = uint8
    PUCHAR* = ptr uint8
    USHORT* = uint16
    PUSHORT* = ptr uint16
    ULONG* = int32
    PULONG* = ptr int32
    SCHAR* = int8
    WINBOOL* = int32
    BOOL* = int32
    LONGLONG* = int64
    PLONGLONG* = ptr int64
    ULONGLONG* = int64
    PULONGLONG* = ptr int64
    PCHAR* = cstring
    LPCH* = cstring
    PCH* = cstring
    LPCCH* = cstring
    PCCH* = cstring
    NPSTR* = cstring
    LPSTR* = cstring
    PSTR* = cstring
    LPCSTR* = cstring
    PCSTR* = cstring
    PSZ* = cstring
    PCSZ* = cstring
    WCHAR* = uint16
    CCHAR* = char
    PCCHAR* = cstring
    NT_PRODUCT_TYPE* = int32
    PNT_PRODUCT_TYPE* = ptr int32
    EVENT_TYPE* = int32
    TIMER_TYPE* = int32
    WAIT_TYPE* = int32
    BYTE* = uint8
    WORD* = uint16
    DWORD* = int32
    PINT* = ptr int32
    LPINT* = ptr int32
    LPLONG* = ptr int32
    LPVOID* = pointer
    LPCVOID* = pointer
    UINT* = int32
    PUINT* = ptr int32
    UCSCHAR* = int32
    PZZSTR* = cstring
    PCZZSTR* = cstring
    PNZCH* = cstring
    PCNZCH* = cstring
    COMPARTMENT_ID* = int32
    PCOMPARTMENT_ID* = ptr int32
    SID_NAME_USE* = int32
    PSID_NAME_USE* = ptr int32
    WELL_KNOWN_SID_TYPE* = int32
    ACL_INFORMATION_CLASS* = int32
    AUDIT_EVENT_TYPE* = int32
    PAUDIT_EVENT_TYPE* = ptr int32
    ACCESS_REASON_TYPE* = int32
    SECURITY_IMPERSONATION_LEVEL* = int32
    PSECURITY_IMPERSONATION_LEVEL* = ptr int32
    TOKEN_TYPE* = int32
    TOKEN_ELEVATION_TYPE* = int32
    PTOKEN_ELEVATION_TYPE* = ptr int32
    TOKEN_INFORMATION_CLASS* = int32
    PTOKEN_INFORMATION_CLASS* = ptr int32
    MANDATORY_LEVEL* = int32
    PMANDATORY_LEVEL* = ptr int32
    SE_LEARNING_MODE_DATA_TYPE* = int32
    HARDWARE_COUNTER_TYPE* = int32
    PHARDWARE_COUNTER_TYPE* = ptr int32
    PROCESS_MITIGATION_POLICY* = int32
    PPROCESS_MITIGATION_POLICY* = ptr int32
    JOBOBJECT_RATE_CONTROL_TOLERANCE* = int32
    JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL* = int32
    JOBOBJECTINFOCLASS* = int32
    FIRMWARE_TYPE* = int32
    PFIRMWARE_TYPE* = ptr int32
    LOGICAL_PROCESSOR_RELATIONSHIP* = int32
    PROCESSOR_CACHE_TYPE* = int32
    SYSTEM_POWER_STATE* = int32
    PSYSTEM_POWER_STATE* = ptr int32
    POWER_ACTION* = int32
    PPOWER_ACTION* = ptr int32
    DEVICE_POWER_STATE* = int32
    PDEVICE_POWER_STATE* = ptr int32
    MONITOR_DISPLAY_STATE* = int32
    PMONITOR_DISPLAY_STATE* = ptr int32
    USER_ACTIVITY_PRESENCE* = int32
    PUSER_ACTIVITY_PRESENCE* = ptr int32
    LATENCY_TIME* = int32
    POWER_REQUEST_TYPE* = int32
    PPOWER_REQUEST_TYPE* = ptr int32
    POWER_INFORMATION_LEVEL* = int32
    POWER_USER_PRESENCE_TYPE* = int32
    PPOWER_USER_PRESENCE_TYPE* = ptr int32
    POWER_MONITOR_REQUEST_REASON* = int32
    SYSTEM_POWER_CONDITION* = int32
    POWER_PLATFORM_ROLE* = int32
    PPOWER_PLATFORM_ROLE* = ptr int32
    IMAGE_AUX_SYMBOL_TYPE* = int32
    IMPORT_OBJECT_TYPE* = int32
    IMPORT_OBJECT_NAME_TYPE* = int32
    ReplacesCorHdrNumericDefines* = int32
    RTL_UMS_THREAD_INFO_CLASS* = int32
    PRTL_UMS_THREAD_INFO_CLASS* = ptr int32
    RTL_UMS_SCHEDULER_REASON* = int32
    PRTL_UMS_SCHEDULER_REASON* = ptr int32
    HEAP_INFORMATION_CLASS* = int32
    ACTIVATION_CONTEXT_INFO_CLASS* = int32
    ACTCTX_REQUESTED_RUN_LEVEL* = int32
    ACTCTX_COMPATIBILITY_ELEMENT_TYPE* = int32
    SERVICE_NODE_TYPE* = int32
    SERVICE_LOAD_TYPE* = int32
    SERVICE_ERROR_TYPE* = int32
    TAPE_DRIVE_PROBLEM_TYPE* = int32
    TP_CALLBACK_PRIORITY* = int32
    TRANSACTION_OUTCOME* = int32
    TRANSACTION_STATE* = int32
    TRANSACTION_INFORMATION_CLASS* = int32
    TRANSACTIONMANAGER_INFORMATION_CLASS* = int32
    RESOURCEMANAGER_INFORMATION_CLASS* = int32
    ENLISTMENT_INFORMATION_CLASS* = int32
    KTMOBJECT_TYPE* = int32
    PKTMOBJECT_TYPE* = ptr int32
    HFILE* = int32
    FILE_INFORMATION_CLASS* = int32
    PFILE_INFORMATION_CLASS* = ptr int32
    FS_INFORMATION_CLASS* = int32
    PFS_INFORMATION_CLASS* = ptr int32
    THREAD_STATE* = int32
    KWAIT_REASON* = int32
    PROCESSINFOCLASS* = int32
    THREADINFOCLASS* = int32
    SYSTEM_INFORMATION_CLASS* = int32
    OBJECT_INFORMATION_CLASS* = int32
    POBJECT_INFORMATION_CLASS* = ptr int32
    WINSTATIONINFOCLASS* = int32
    HANDLE* = int
    VOID* = void
    PVOID64* = pointer
    va_list* = pointer
    FARPROC* = pointer
    NEARPROC* = pointer
    PROC* = pointer
    EXCEPTION_DISPOSITION* = int
    QWORD* = int64
    PQWORD* = ptr int64